workflows:
  max-voice-assistant:
    name: Max Voice Assistant
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
